# Generated by Django 4.2.13 on 2024-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_bookings_user_email_alter_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_time',
            field=models.TimeField(max_length=100),
        ),
    ]
