# Generated by Django 5.1.5 on 2025-01-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_bookings_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('reservation', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('speacial_offers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
