# Generated by Django 5.1.5 on 2025-01-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='speacial_offers',
            new_name='special_offers',
        ),
    ]
