# Generated by Django 5.1.5 on 2025-01-27 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='restaurant_name',
            field=models.CharField(default='Jkspices', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
